version: "3.8"

services:
  bot:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    container_name: chatbot_sa_bot
    volumes:
      - /home/ubuntu/.ssh/github_deploy:/root/.ssh/id_ed25519:ro
    environment:
      - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no
    restart: unless-stopped
