version: "3.8"

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    container_name: chatbot_sa_bot
    volumes:
      - type: bind
        source: /home/ubuntu/.ssh/github_deploy
        target: /root/.ssh/id_ed25519
        read_only: true
    environment:
      - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - "8000:8000"
    restart: unless-stopped
