name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            set -e
            cd ~/chatbot_sa
            echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" > .secrets/.env
            docker-compose down
            docker-compose up -d --build
          EOF
